
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 20 14:22:43 BRST 2007
//----------------------------------------------------

package odog.ruleChecker;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 37;
  public static final int REQSERV = 11;
  public static final int GE = 32;
  public static final int EX_AR = 18;
  public static final int ATTRCLASS = 7;
  public static final int HVER = 9;
  public static final int RBRAC = 35;
  public static final int SEMICOLON = 38;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int LT = 31;
  public static final int RPAR = 22;
  public static final int OR = 24;
  public static final int TOPOLOGY = 5;
  public static final int DPORT = 2;
  public static final int DOT = 20;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int COMPONENTINSTANCE = 6;
  public static final int METHOD = 12;
  public static final int EXPORTEDPORT = 14;
  public static final int error = 1;
  public static final int CONNECTION = 13;
  public static final int EX_CM = 19;
  public static final int DEFVER = 15;
  public static final int ACOMP = 3;
  public static final int EQ = 28;
  public static final int IMPLY = 26;
  public static final int IFONLYIF = 27;
  public static final int VER = 8;
  public static final int ATTR = 4;
  public static final int COLON = 39;
  public static final int LPAR = 21;
  public static final int DIFF = 29;
  public static final int LBRAC = 34;
  public static final int VALUE = 10;
  public static final int GT = 30;
  public static final int PT_QUAL = 16;
  public static final int EX_QUAL = 17;
  public static final int IDENTIFIER = 36;
}

